//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalServices.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    public partial class Medicamento_Tratamiento
    {
        public int ID { get; set; }
        public Nullable<int> ID_Medicamento { get; set; }
        public Nullable<int> ID_Tratamiento { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Medicamento Medicamento { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
